CREATE TABLE IF NOT EXISTS debts (
  id TEXT NOT NULL PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  type INTEGER NOT NULL DEFAULT 0,
  iconId TEXT NOT NULL DEFAULT 'no_icon',
  currencyId TEXT NOT NULL REFERENCES currencies(code) ON DELETE CASCADE ON UPDATE CASCADE,
  initialAmount REAL NOT NULL DEFAULT 0,
  startDate TEXT NOT NULL,
  endDate TEXT
);

ALTER TABLE transactions ADD COLUMN debtId TEXT REFERENCES debts(id) ON DELETE SET NULL;
