PRAGMA foreign_keys = OFF;

CREATE TABLE IF NOT EXISTS transactions_temp (
  id TEXT NOT NULL PRIMARY KEY,
  date DATETIME NOT NULL,
  accountID TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE ON UPDATE CASCADE,
  value REAL NOT NULL,
  title TEXT,
  notes TEXT,
  type TEXT NOT NULL CHECK(type IN ('E', 'I', 'T')),
  status TEXT CHECK(status IN ('V', 'P', 'R', 'U')),
  categoryID TEXT REFERENCES categories(id) ON DELETE CASCADE ON UPDATE CASCADE,
  debtId TEXT REFERENCES debts(id) ON DELETE SET NULL ON UPDATE CASCADE,
  valueInDestiny REAL,
  receivingAccountID TEXT REFERENCES accounts(id) ON DELETE CASCADE ON UPDATE CASCADE,
  isHidden BOOLEAN NOT NULL DEFAULT 0,
  exchangeRateApplied REAL,
  exchangeRateSource TEXT CHECK(exchangeRateSource IN ('bcv','paralelo','manual','auto')),
  createdBy TEXT REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE,
  modifiedBy TEXT REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modifiedAt DATETIME,
  locLatitude REAL,
  locLongitude REAL,
  locAddress TEXT,
  intervalPeriod TEXT CHECK(intervalPeriod IN ('day','week','month','year')),
  intervalEach INTEGER,
  endDate DATETIME,
  remainingTransactions INTEGER,

  CHECK ((receivingAccountID IS NULL) != (categoryID IS NULL)),
  CHECK ((intervalPeriod IS NULL) == (intervalEach IS NULL)),
  CHECK ((intervalPeriod IS NOT NULL) OR (endDate IS NULL)),
  CHECK ((intervalPeriod IS NOT NULL) OR (remainingTransactions IS NULL)),
  CHECK ((locLongitude IS NULL AND locLatitude IS NULL) OR (locLongitude IS NOT NULL AND locLatitude IS NOT NULL)),
  CHECK ((locAddress IS NULL) OR (locLatitude IS NOT NULL AND locLongitude IS NOT NULL)),
  CHECK (categoryID IS NULL OR valueInDestiny IS NULL)
);

INSERT INTO transactions_temp (
  id,
  date,
  accountID,
  value,
  title,
  notes,
  type,
  status,
  categoryID,
  debtId,
  valueInDestiny,
  receivingAccountID,
  isHidden,
  exchangeRateApplied,
  exchangeRateSource,
  createdBy,
  modifiedBy,
  createdAt,
  modifiedAt,
  locLatitude,
  locLongitude,
  locAddress,
  intervalPeriod,
  intervalEach,
  endDate,
  remainingTransactions
)
SELECT
  id,
  date,
  accountID,
  value,
  title,
  notes,
  type,
  status,
  categoryID,
  debtId,
  valueInDestiny,
  receivingAccountID,
  isHidden,
  exchangeRateApplied,
  exchangeRateSource,
  createdBy,
  modifiedBy,
  createdAt,
  modifiedAt,
  locLatitude,
  locLongitude,
  locAddress,
  intervalPeriod,
  intervalEach,
  endDate,
  remainingTransactions
FROM transactions;

DROP TABLE transactions;
ALTER TABLE transactions_temp RENAME TO transactions;

PRAGMA foreign_keys = ON;
