import 'package:kilatex/core/utils/uuid.dart';

/// Sizes a [WidgetDescriptor] can declare. The MVP only supports two
/// declarative sizes — the user does not freely resize widgets.
///
/// - [WidgetSize.medium]   ≈ 50% of the dashboard width (grid 2-col).
/// - [WidgetSize.fullWidth] = 100% of the dashboard width.
enum WidgetSize {
  medium,
  fullWidth;

  /// Best-effort decoder. Returns `null` when [raw] is `null` or unknown so
  /// the migrator can decide whether to drop the descriptor or apply a
  /// default.
  static WidgetSize? tryParse(String? raw) {
    if (raw == null) return null;
    for (final value in WidgetSize.values) {
      if (value.name == raw) return value;
    }
    return null;
  }
}

/// Closed enum of the MVP catalog. Adding a new widget type requires:
///   1. Add the enum entry here.
///   2. Register a [DashboardWidgetSpec] in `registry_bootstrap.dart`.
///   3. Update the [DashboardLayoutMigrator] only if older payloads should
///      be rewritten to use the new type.
enum WidgetType {
  totalBalanceSummary,
  accountCarousel,
  incomeExpensePeriod,
  recentTransactions,
  exchangeRateCard,
  quickUse,
  pendingImportsAlert;

  /// Best-effort decoder. Returns `null` when [raw] is `null` or unknown.
  /// Unknown types are dropped silently by the migrator (the layout still
  /// loads) so we never abort because of a future-version payload.
  static WidgetType? tryParse(String? raw) {
    if (raw == null) return null;
    for (final value in WidgetType.values) {
      if (value.name == raw) return value;
    }
    return null;
  }
}

/// Quick-action identifiers used by the `quickUse` widget. Stored inside
/// `WidgetDescriptor.config['chips']` as a `List<String>` of `name`s.
///
/// The dispatcher (`QuickActionRegistry`) resolves these to actual callbacks
/// at runtime — keeping them as a typed enum here means the layout JSON
/// stays stable and unknown ids are dropped silently.
enum QuickActionId {
  togglePrivateMode,
  toggleHiddenMode,
  togglePreferredCurrency,
  goToSettings,
  newExpenseTransaction,
  newIncomeTransaction,
  newTransferTransaction,
  goToBudgets,
  goToReports,
  openTransactions,
  openExchangeRates,
  // NEW (calculadora-fx Tanda 1, task 1.4): SIEMPRE al final del enum.
  // El `name` se persiste en el layout JSON del dashboard, así que cualquier
  // reordenamiento rompería los chips guardados de los usuarios existentes.
  goToCalculator;

  /// Best-effort decoder. Returns `null` when [raw] is `null` or unknown.
  static QuickActionId? tryParse(String? raw) {
    if (raw == null) return null;
    for (final value in QuickActionId.values) {
      if (value.name == raw) return value;
    }
    return null;
  }
}

/// Immutable description of one widget instance inside a [DashboardLayout].
///
/// Two descriptors in the same layout MUST have distinct [instanceId]s;
/// duplicates are regenerated by the migrator on load (see spec
/// `dashboard-layout` § Modelo `WidgetDescriptor`).
///
/// `config` is intentionally `Map<String, dynamic>`. Each [WidgetType]
/// declares its own contract via `DashboardWidgetSpec.defaultConfig` —
/// extra keys are tolerated (forward compatibility).
class WidgetDescriptor {
  final String instanceId;
  final WidgetType type;
  final WidgetSize size;
  final Map<String, dynamic> config;

  const WidgetDescriptor({
    required this.instanceId,
    required this.type,
    required this.size,
    this.config = const <String, dynamic>{},
  });

  /// Convenience constructor that generates a fresh uuid v4 [instanceId].
  /// Used when the user adds a widget from the catalog sheet.
  factory WidgetDescriptor.create({
    required WidgetType type,
    required WidgetSize size,
    Map<String, dynamic>? config,
  }) {
    return WidgetDescriptor(
      instanceId: generateUUID(),
      type: type,
      size: size,
      config: config == null
          ? const <String, dynamic>{}
          : Map<String, dynamic>.from(config),
    );
  }

  /// Returns a JSON-friendly map. Only enum `name`s and primitive values are
  /// emitted — the result is safe to pass to `jsonEncode` straight away.
  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'instanceId': instanceId,
      'type': type.name,
      'size': size.name,
      'config': Map<String, dynamic>.from(config),
    };
  }

  /// Best-effort decoder. Returns `null` when:
  ///   - [json] is missing required keys, or
  ///   - [type] / [size] are unknown (future schema), or
  ///   - [instanceId] is missing or empty.
  ///
  /// Caller (migrator) is responsible for deciding whether a `null` means
  /// "drop this descriptor" or "regenerate the missing field".
  static WidgetDescriptor? fromJson(Map<String, dynamic> json) {
    final rawInstanceId = json['instanceId'];
    final type = WidgetType.tryParse(json['type'] as String?);
    final size = WidgetSize.tryParse(json['size'] as String?);
    if (type == null || size == null) return null;

    final instanceId = rawInstanceId is String && rawInstanceId.isNotEmpty
        ? rawInstanceId
        : generateUUID();

    final rawConfig = json['config'];
    final config = rawConfig is Map
        ? Map<String, dynamic>.from(rawConfig)
        : <String, dynamic>{};

    return WidgetDescriptor(
      instanceId: instanceId,
      type: type,
      size: size,
      config: config,
    );
  }

  WidgetDescriptor copyWith({
    String? instanceId,
    WidgetType? type,
    WidgetSize? size,
    Map<String, dynamic>? config,
  }) {
    return WidgetDescriptor(
      instanceId: instanceId ?? this.instanceId,
      type: type ?? this.type,
      size: size ?? this.size,
      config: config == null
          ? Map<String, dynamic>.from(this.config)
          : Map<String, dynamic>.from(config),
    );
  }

  /// Returns a new descriptor with a freshly generated [instanceId]. Used by
  /// the migrator to dedup duplicate ids inside a single layout.
  WidgetDescriptor withRegeneratedId() {
    return copyWith(instanceId: generateUUID());
  }

  @override
  String toString() =>
      'WidgetDescriptor(instanceId: $instanceId, type: ${type.name}, '
      'size: ${size.name}, config: $config)';
}
